spring:
  application:
    name: mts 2_sem
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: password

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown
      base-path: /admin

resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slidingWindowSize: 100
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10000ms
        permittedNumberOfCallsInHalfOpenState: 5
        eventConsumerBufferSize: 10
        ringBufferSizeInClosedState: 100
        ringBufferSizeInHalfOpenState: 10

  ratelimiter:
    instances:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms