spring:
  application:
    name: mts 2_sem
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: password

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown
      base-path: /admin
